;; # coding: utf-8
;; パッケージリポジトリの指定
(source gnu)
(source melpa)
(source marmalade)

(depends-on "magit")
(depends-on "dracula-theme")
(depends-on "auto-complete")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-ag" "0.57" )
(depends-on "helm-swoop")
(depends-on "helm-gtags")
;; (depends-on "gtags-mode")

(depends-on "scss-mode")
(depends-on "haml-mode")
(depends-on "yaml-mode")
(depends-on "ruby-mode")
(depends-on "coffee-mode")
(depends-on "web-mode")
(depends-on "direx")
(depends-on "whitespace")
(depends-on "tabbar")
(depends-on "git-gutter-fringe+")
(depends-on "visual-regexp")
(depends-on "visual-regexp-steroids")
(depends-on "pcre2el")
(depends-on "markdown-mode")
(depends-on "undo-tree")
(depends-on "indent-guide")
(depends-on "indent-tools")
;;(depends-on "")

;; default
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
